sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t padmender/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true padmender/docker-react npm run test

